env:
  browser: true
  es6: true
extends: 'plugin:prettier/recommended'
globals:
  browser: readonly
  chrome: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "no-trailing-spaces": "error",
  "indent": ["error", 2, {"SwitchCase": 1}],
  "no-multi-spaces": "error",
  "eqeqeq": "error"
}
