env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:sonarjs/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:total-functions/recommended'
plugins:
  - 'sonarjs'
  - 'prettier'
  - 'total-functions'
globals:
  browser: readonly
  chrome: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 2018
  sourceType: "module"
rules: {
  # Additional rules that are not part of `eslint:recommended`.
  # See https://eslint.org/docs/rules/
  "no-eval": "error",
  "no-implied-eval": "error",
  "no-await-in-loop": "error",
  "no-new-wrappers": "error",
  "no-trailing-spaces": "error",
  "indent": ["error", 2, {"SwitchCase": 1}],
  "no-multi-spaces": "error",
  "eqeqeq": "error"
}
